services:
  web:
    build:
      context: .
      args:
        - PORT=${PORT:-4000}
    ports:
      - "127.0.0.1:${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./data:/code/data
    env_file:
      - .env
    environment:
      - DEV_MODE=${DEV_MODE:-false}
      - PORT=${PORT:-4000}
